package seng302.group5.controller.dialogControllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TextArea;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;
import seng302.group5.controller.enums.CreateOrEdit;

public class EffortDialogController {

  @FXML private Button btnConfirm;
  @FXML private Button btnCancel;
  @FXML private HBox btnContainer;

  @FXML private ComboBox teamMemberCombo;
  @FXML private DatePicker dateField;
  @FXML private TextArea commentField;

  private TaskDialogController taskDC;
  private Stage thisStage;
  private CreateOrEdit createOrEdit;

  /**
   * Sets up the EffortDialogController.
   * @param taskDC The task dialog controller for the effort to be added to.
   * @param thisStage The stage of the dialog.
   * @param createOrEdit Whether this dialog is for creating or editing.
   */
  public void setupController(TaskDialogController taskDC, Stage thisStage, CreateOrEdit createOrEdit) {
    this.taskDC = taskDC;
    this.thisStage = thisStage;
    this.createOrEdit = createOrEdit;

    String os = System.getProperty("os.name");

    if (!os.startsWith("Windows")) {
      btnContainer.getChildren().remove(btnConfirm);
      btnContainer.getChildren().add(btnConfirm);
    }

    if (createOrEdit == CreateOrEdit.CREATE) {
      thisStage.setTitle("Log New Effort");
      btnConfirm.setText("Log");
    } else if (createOrEdit == CreateOrEdit.EDIT) {
      thisStage.setTitle("Edit Logged Effort");
      btnConfirm.setText("Save");

      //TODO: Populate fields.
    }

    this.createOrEdit = createOrEdit;
    btnConfirm.setDefaultButton(true);
    thisStage.setResizable(false);
  }

  /**
   * Adds the effort to the tesk.
   *
   * @param event Event generated by event listener.
   */
  @FXML
  private void btnConfirmClick(ActionEvent event) {
    System.out.println(teamMemberCombo.getSelectionModel().getSelectedItem());
    System.out.println(dateField.toString());
    System.out.println(commentField.getText().trim());
  }

  /**
   * Closes the Effort dialog box on click of 'Cancel' button.
   *
   * @param event Event generated by event listener.
   */
  @FXML
  private void btnCancelClick(ActionEvent event) {
    thisStage.close();
  }
}
