package seng302.group5.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import seng302.group5.Main;
import seng302.group5.model.Person;

/**
 * Created by Zander on 18/03/2015.
 */
public class PersonDialogController {

  private Main mainApp;
  private Stage thisStage;

  @FXML private TextField uniqueShortName;
  @FXML private TextField firstName;
  @FXML private TextField lastName;

  /**
   * Sets the current instance of Main as mainApp.
   * @param mainApp Current instance of Main.
   */
  public void setMainApp(Main mainApp){
    this.mainApp = mainApp;
  }

  public void setStage(Stage stage) {
    this.thisStage = stage;
  }

  /**
   * Creates a new Person from the textfield data
   * on click of 'Create' button.
   *
   * @param event Event generated by event listener.
   */
  @FXML
  protected void btnCreatePersonClick(ActionEvent event) {
    String shortName = uniqueShortName.getText();

    if (checkShortNameValidity(shortName) == true) {
      mainApp.addPerson(shortName, firstName.getText(), lastName.getText());
      thisStage.close();
    }
  }

  /**
   * Closes the CreatePerson dialog box in click of
   * 'Cancel' button.
   *
   * @param event Event generated by event listener.
   */
  @FXML
  protected void btnCancelClick(ActionEvent event) {
    thisStage.close();
  }

  /**
   * Checks whether the a uniqueShortName is valid.
   * It is not-null.
   * It is less than 8 characters in length.
   * It is unique.
   *
   * @param name uniqueShortName to be verified.
   * @return True: name is valid. False: name is not valid.
   */
  private boolean checkShortNameValidity(String name) {
    if (name.length() < 8 && name.length() > 0) {
      for (Person person : mainApp.getPeople()) {
        if (person.getUniqueShortName().equals(name)) {
          System.out.println("Person ID is not unique.");
          return false;
        }
      }
      return true;
    }
    else {
      System.out.println("Person ID is blank or too long.");
      return false;
    }
  }
}
